version: '3.3'
services:

  mysql:
    image: mysql:8.0
    container_name: db-for-go

    # MySQLの設定値を指定
    command: 
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --sql-mode=ONLY_FULL_GROUP_BY,NO_ENGINE_SUBSTITUTION

    # コンテナ内で使用する環境変数の値を指定
    environment:
        MYSQL_ROOT_USER: ${ROOTUSER}
        MYSQL_ROOT_PASSWORD: ${ROOTPASS} 
        MYSQL_DATABASE: ${DATABASE} # MySQL内にある初期データベースの名前
        MYSQL_USER: ${USERNAME}
        MYSQL_PASSWORD: ${USERPASS}
        TZ: 'Asia/Tokyo'

    # コンテナのポートをローカルのポートの3306番に繋げる
    ports: 
        - "3306:3306"

    # コンテナ内にあるMySQLのデータを永続化させるためのボリュームを指定する
    volumes:
        - db-volume:/var/lib/mysql

# ボリュームの作成
volumes:
  db-volume: